let categories = [
  {
    id:'01',
    src:'./assets/images/categories/1.png'
  },
  {
    id:'02',
    src:'./assets/images/categories/2.png'
  },
  {
    id:'03',
    src:'./assets/images/categories/3.png'
  },
  {
    id:'04',
    src:'./assets/images/categories/4.png'
  },
  {
    id:'05',
    src:'./assets/images/categories/5.png'
  },
  {
    id:'06',
    src:'./assets/images/categories/6.png'
  },
  {
    id:'07',
    src:'./assets/images/categories/7.png'
  },
  {
    id:'08',
    src:'./assets/images/categories/8.png'
  },
  {
    id:'09',
    src:'./assets/images/categories/9.png'
  },
  {
    id:'10',
    src:'./assets/images/categories/10.png'
  },
  {
    id:'11',
    src:'./assets/images/categories/11.png'
  },
  {
    id:'12',
    src:'./assets/images/categories/12.png'
  },
]