let spotlightCategories = [
  {
    id:'01',
    src:'./assets/images/categories/spotlight/Allen_Solly.png'
  },
  {
    id:'02',
    src:'./assets/images/categories/spotlight/Arrow.png'
  },
  {
    id:'03',
    src:'./assets/images/categories/spotlight/Bewakoof.png'
  },
  {
    id:'04',
    src:'./assets/images/categories/spotlight/Eyewearlabs.png'
  },
  {
    id:'05',
    src:'./assets/images/categories/spotlight/Levis.png'
  },
  {
    id:'06',
    src:'./assets/images/categories/spotlight/Pepe_Jeans.png'
  },
  {
    id:'07',
    src:'./assets/images/categories/spotlight/Puma.png'
  },
  {
    id:'08',
    src:'./assets/images/categories/spotlight/Red_Tape.png'
  },
  {
    id:'09',
    src:'./assets/images/categories/spotlight/Symbol.png'
  },
  {
    id:'10',
    src:'./assets/images/categories/spotlight/The_Souled_Store.png'
  },
  {
    id:'11',
    src:'./assets/images/categories/spotlight/US_Polo.png'
  },
  {
    id:'12',
    src:'./assets/images/categories/spotlight/XYXX.png'
  },
]